export const AVERAGE_MEASUREMENTS_REQUEST = "AVERAGE_MEASUREMENTS_REQUEST";
export const AVERAGE_MEASUREMENTS_SUCCESS = "AVERAGE_MEASUREMENTS_SUCCESS";
export const AVERAGE_MEASUREMENTS_FAILURE = "AVERAGE_MEASUREMENTS_FAILURE";
